# Generated by Django 4.2.11 on 2024-05-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_post_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="is_displayed",
            field=models.BooleanField(default=True),
        ),
    ]
